### ISSUE TITLE
Error 404 for SPA (Single Page Application)

### ISSUE THREAD

**Issue by paulocoutinhox** [actions/upload-pages-artifact#3] opened 2022-07-29 19:24 UTC
Hi,

Im making a project that is a SPA, and i want host on github instead of Netlify.

But github still not support redirect all to index.html.

How i can do it with this new deploy method?

Repository:
https://github.com/sqlitedb/sqlitedb.github.io

Workflow:
https://github.com/sqlitedb/sqlitedb.github.io/blob/main/.github/workflows/pages.yml

Error:
https://sqlitedb.github.io/about

Thanks.

**Comment by yoannchaudet** [comment] 2022-07-29 20:34
Pages does not support custom redirect but you can leverage our support for a 404.html file. Upload such a file to your repo (e.g. as a duplicate of your index.html) and any path that does not exist in your repo will be served by that file.

The discussions area is a better place for these kind of questions: https://github.com/orgs/community/discussions/. Closing this issue but feel free to open a discussion on the other side if you need further information.

**Closed by yoannchaudet** 2022-07-29 20:34 UTC

**Comment by paulocoutinhox** [comment] 2022-07-30 02:14
Hi,

Yes, im using it, bad show http status 404.

I open a discussion here:
https://github.com/orgs/community/discussions/27676

Thanks.
